### ISSUE TITLE
Environment scope needs to be a part of the gitlab_project_variable ID

### ISSUE THREAD

**Issue by lindehoff** [terraform-providers/terraform-provider-gitlab#235] opened 2019-12-20 10:20 UTC
Hi,
I have two different terraform projects that create a gitlab_project_variable with the same name but with different environment_scope. Everything works when I run terraform apply and the variables are created correctly. But if I run terraform apply again for the first project it what's to update the variable being created from the second project.

I have found the problem being that the resource ID is based on `projectID:variableName` but since you can have multiple instance of the same variable name inside a gitlab project this needs to change to perhaps `projectID:scopeName:variableName` 

### Terraform Version
Terraform v0.12.17

### Affected Resource(s)
- gitlab_project_variable

**Comment by roidelapluie** [comment] 2019-12-20 10:33
dupe of #213

**Closed by roidelapluie** 2019-12-20 10:33 UTC
