### ISSUE TITLE
New soft delete feature in GL 12.6 breaks gitlab_project delete.

### ISSUE THREAD

**Issue by flacito** [terraform-providers/terraform-provider-gitlab#272] opened 2020-03-06 20:23 UTC
Hi there,

### Terraform Version
Terraform v0.12.20

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this: **only this single resource, so not applicable**.

### Terraform Configuration Files
```hcl
resource "gitlab_group" "example" {
  name        = "Example"
  path        = "Example"
  description = "Example group."
}

resource "gitlab_project" "example" {
  name         = "Example"
  path         = "example"
  namespace_id = gitlab_group.example.id
  description  = "Example project."
  shared_runners_enabled = true
  initialize_with_readme = true
}
```

### Debug Output
```
gitlab_project.example["example"]: Still destroying... [id=5213, 10m0s elapsed]
Error: error waiting for project (5213) to become deleted: timeout while waiting for state to become 'Deleted' (last state: 'Deleting', timeout: 10m0s)
 ```
### Panic Output
none

### Expected Behavior
gitlab_project resource delete should not timeout waiting for Deleted state

### Actual Behavior
gitlab_project resource delete does timeout waiting for Deleted state, stays in Deleting state because of new GitLab feature here: <https://docs.gitlab.com/ee/api/projects.html#remove-project>. GitLab, Inc. added a soft delete where the project will not actually change to Deleted until 7 days.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Use GitLab Silver or higher or a premium on prem GitLab server
1. `terraform apply` the above Terraform Configuration
1. `terraform delete` the above Terraform Configuration and it will timeout waiting for Delete state

### Important Factoids
Probably just need to think about making an assumption of calling the gitlab_project resource successful if the state is either Deleted or Deleting and provide an attribute for the user to ignore the soft delete (see below)  The users don't see the project if in Deleting state even though it's still in the system. However, there will be complications if the user goes back in and restores the project.  Not an easy problem to fix.

This is just a suggestion:

```
resource "gitlab_project" "example" {
  name         = "Example"
  path         = "example"
  namespace_id = gitlab_group.example.id
  description  = "Example project."
  shared_runners_enabled = true
  initialize_with_readme = true
  deleting_state_for_delete = true
}
```
When `terraform destroy` the project goes into the Deleting state and the resource treats that as success.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://docs.gitlab.com/ee/api/projects.html#remove-project
- https://github.com/flacito/terraform-provider-gitlab/blob/02b1bd323f502594419e1731f11cd1fbdc66b2e3/gitlab/resource_gitlab_project.go#L537

**Comment by ilpianista** [comment] 2020-03-09 15:17
Isn't this a duplicate of #263?

**Comment by ringods** [comment] 2020-03-23 20:10
Indeed, duplicate of #263. I'm working on getting the acceptance tests working correctly before more contributions can be accepted.

**Closed by ringods** 2020-03-23 20:10 UTC
