### ISSUE TITLE
Deploy keys will stop being idempotent because the key comment will be masked in the upcoming 13.1 release of Gitlab

### ISSUE THREAD

**Issue by Wiebelt** [terraform-providers/terraform-provider-gitlab#338] opened 2020-06-17 12:18 UTC
### Terraform Version
v0.12.26 with v2.10.0 gitlab provider

### Affected Resource(s)
- gitlab_deploy_key

### Expected Behavior
No changes should be made.

### Actual Behavior
Terraform wants to change the key because Gitlab redacts the key comment and it will always append the Gitlab username.

```
Terraform will perform the following actions:

# gitlab_deploy_key.test must be replaced
-/+ resource "gitlab_deploy_key" "test" {
        can_push = false
      ~ id       = "42" -> (known after apply)
      ~ key      = "ssh-ed25519 REDACTED Wiebelt (gitlab.com)" -> "ssh-ed25519 REDACTED" # forces replacement
        project  = "9034590"
        title    = "test key"
    }
```

### Steps to Reproduce
Gitlab.com is already running a pre-release of 13.1 (which is why we ran into this problem.

### Possible fix
Modify the [DiffSurpressFunc](https://github.com/terraform-providers/terraform-provider-gitlab/pull/34/files#diff-34a373a6c4dfea51f2e4e4d857476564R34) to not only ignore newlines but also ignore the SSH key comment and the Gitlab username. This was introduced in https://github.com/terraform-providers/terraform-provider-gitlab/pull/34

### References
[Gitlab issue with reasons why they changed this](https://gitlab.com/gitlab-org/gitlab/-/issues/220185)
[Gitlab merged merge request](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/34255)

**Comment by Wiebelt** [comment] 2020-06-17 12:23
You can easily workaround this for now by the way by appending the Gitlab username to the SSH key.

**Comment by oboukili** [comment] 2020-06-19 13:05
@Wiebelt unfortunately this only works in a single tenant situation where a single user runs terraform, Gitlab will rewrite the comment with the token current username.

**Comment by Wiebelt** [comment] 2020-06-19 14:20
@oboukili do you mean the workaround? Because, yes that is a problem and why Terraform should just ignore the comment all together.
I'm not in a situation where the deploy keys change often so I've just copied the different usernames being used for now until this is fixed.

**Comment by roidelapluie** [comment] 2020-06-22 10:21
Please see https://gitlab.com/gitlab-org/gitlab/-/issues/223218#note_365493446 - should be fixed in gitlab 13.2

**Comment by abitrolly** [comment] 2020-06-22 18:03
Is it the reason why acceptance test are failing for PRs? https://github.com/terraform-providers/terraform-provider-gitlab/runs/796242211

**Comment by roidelapluie** [comment] 2020-06-22 18:20
Yes but gitlab will fix this in 1.13.1

**Comment by abitrolly** [comment] 2020-06-23 03:18
@roidelapluie any guesses when it may happen?

**Comment by pdecat** [comment] 2020-06-23 05:58
What about pinning gitlab/gitlab-ce image to `13.0.6-ce.0` in to make acceptance tests pass again for the time being?

https://github.com/terraform-providers/terraform-provider-gitlab/blob/v2.10.0/scripts/start-gitlab.sh#L14

**Comment by roidelapluie** [comment] 2020-06-26 08:38
gitlab has issues 13.1.1 which resolves this.

**Closed by roidelapluie** 2020-06-26 08:38 UTC

**Comment by pdecat** [comment] 2020-06-26 09:39
The deploy key issue was indeed resolved by Gitlab 13.1.1but now JIRA service tests fail:

```sh
# MAKE_TARGET=testacc scripts/start-gitlab.sh
Starting gitlab container...
dfd4ea69b610401cf74ff8a1f5d2803d0ee460ef2bc2a4679925db15b5746869
Waiting for gitlab to be ready ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... .
Creating access token



--------------------------------------------------------------------------------
 GitLab:       13.1.1 (bdb9883705a) FOSS
 GitLab Shell: 13.3.0
 PostgreSQL:   11.7
--------------------------------------------------------------------------------
Loading production environment (Rails 6.0.3.1)
Switch to inspect mode.
terraform_token = PersonalAccessToken.create(user_id: 1, scopes: [:api, :read_user], name: :terraform);terraform_token.set_token('ACCTEST');terraform_token.save!;
true

# make testacc TEST=./gitlab TESTARGS='-run TestAccGitlabServiceJira_basic -count 1'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test -v ./gitlab -run TestAccGitlabServiceJira_basic -count 1 -timeout 40m
=== RUN   TestAccGitlabServiceJira_basic
    TestAccGitlabServiceJira_basic: testing.go:684: Step 1 error: Check failed: Check 2/8 error: gitlab_service_jira.jira: Attribute 'url' expected "https://testurl.com", got "https://test.com"
--- FAIL: TestAccGitlabServiceJira_basic (10.67s)
FAIL
FAIL    github.com/terraform-providers/terraform-provider-gitlab/gitlab 10.684s
FAIL
make: *** [GNUmakefile:23: testacc] Error 1
```

https://github.com/claranet/terraform-provider-gitlab/runs/810546410

**Comment by pdecat** [comment] 2020-06-26 09:41
What about running acceptance tests against a set of "supported" gitlab/gitlab-ce image tags like 13.0.6-ce.0 in addition to latest to identify API behavior changes faster?

**Comment by abitrolly** [comment] 2020-06-26 09:50
@pdecat send PR?

**Comment by pdecat** [comment] 2020-06-26 11:30
Turns out the JIRA test issue is not caused by Gitlab 13.1.1, it also fails with 13.0.6: https://github.com/claranet/terraform-provider-gitlab/runs/810649101
